### ISSUE TITLE
not able to connect on chrome

### ISSUE THREAD

**Issue by kingcoyote** [jfd/wpilot#11]
I  have a weird issue that I'm trying to debug, but since my knowledge of wpilot's code is fairly minimal, I'm having trouble even figuring out where to look.

I've got the exact same set of files on two computers, one at work and one at home. The work computer is Ubuntu 10.10 with Chromium 12. The home computer is 11.04, but I can't recall the version of Chromium.

When I launch wpilot, it works perfectly fine at home. But on my work computer, Chromium fails to connect. I get to the first screen where I choose my name, hit Continue, and then hit Join Server. At this point, it just says 'You were disconnected from server "Unknown reason"'. However, if I use Firefox on the same computer, it works fine.

But, I can use this exact computer and browser to connect to other wpilot servers, like the ones listed on the github page or a server set up on another machine here at work.

I've been trying to add breakpoints both on the client side and the server side, but I can't even figure out where to start looking. Unfortunately, this problem seems so incredibly unique that I don't foresee good odds with you being able to replicate it. So I'm doing what I can to patch it on this environment, but I'm at a loss for where to start poking around.

Any ideas?

**Comment by jfd** [comment]
Yes, Im aware of this issue. Newer version (developer channel) of chrome are using the new WebSocket specification, which is not compatible with the current WebSocket server that is powering WPilot.

**Comment by kingcoyote** [comment]
That seems odd. This browser can run wpilot, it only seems to have issue when it's connecting to the wpilot that is on the same machine, regardless of what hostname I use (I've tried 127.0.0.1, localhost, 192.168.0.126)

All of these connections work:
work chrome -> work wpilot
work firefox -> work wpilot
work firefox -> localhost wpilot
home chrome -> home wpilot

The only one that fails is work chrome -> localhost wpilot. If it was just a general issue with my Chromium browser, wouldn't it have trouble connecting to the work wpilot server? It's running an identical build of wpilot as my localhost is.

Definitions:
work chrome - My work computer running the Chromium browser
work firefox - My work computer running Firefox
work wpilot - A server in the building running a wpilot server (v1.1)
localhost wpilot - My work computer running a wpilot server (v1.1, literally copy/pasted from work wpilot)
home chrome - My home computer running Chromium
home wpilot - My home computer running a wpilot server (v1.1)

**Comment by sergeyuk** [comment]
Yeah, got the same issue, seems the latest Chrome update broke everything. 
Works only if I connect from another machine i.e. not to localhost.

The interesting thing is that I've just installed FF6 and it says "Your browser doesnt support WebSocket or Flash". 
network.websocket.enabled = true by default there and I guess the whole reason to have Flash stuff is to get websocket work even in absolutely crappy browsers like IE and it doesn't work in the latest firefox.

websockets doesn't seem to be reliable, any good alternatives for browser-gamedev?

**Comment by jfd** [comment]
Chrome might have some issue with connecting to localhost. I know that they sometimes throws a security exception when trying to access local files via XmlHttpRequest.  I do not run chrome, so I can't test this. Have you tried to google it, see if there is a settings for this, or, even better, a solution? 

FF6 has support for websocket v7. The WebSocket server powered by Wpilot does not support this. I might tweak it some day, but it feels kind of a time waste. The v7 is just temporary and will be replaced by v10 very soon

**Comment by jfd** [comment]
Fixed in ce89233d8fd4c995f138a035076af0784ce502b2
