### ISSUE TITLE
newest version won't work on FireFox latest

### ISSUE THREAD

**Issue by Truemedia** [jfd/wpilot#13]
Latest version of firefox when attempting to connect gets stuck on 'Connecting' and the actions headlines "Trying to connect to server"

**Comment by jfd** [comment]
Never versions of Firefox is using the new HyBi protocol standard. The WPilot server only supports Hixie at the moment

**Comment by Truemedia** [comment]
Yeh I thought it was along the lines of a new standard, may look into and offer a commit myself

**Comment by jfd** [comment]
That would be appreciated!

**Comment by jfd** [comment]
Fixed in ce89233d8fd4c995f138a035076af0784ce502b2
