### ISSUE TITLE
all servers down

### ISSUE THREAD

**Issue by jancborchardt** [jfd/wpilot#17]
All the game servers appear to be down. It would be cool if there would be at least one server for playing & demo purposes.

**Comment by jfd** [comment]
The server that is online is not supporting the new WebSocket protocol. I think that Safari still using the old protocol, you could try with that.

**Comment by neuhaus** [comment]
I think using ws (https://npmjs.org/package/ws) might be the best option.
OTOH, websocket seems to have matured and is no longer a quick moving target.

**Comment by jfd** [comment]
The new WebSocket interface is Implemented in ce89233d8fd4c995f138a035076af0784ce502b2    Will take some time to update the online-servers though

**Comment by neuhaus** [comment]
I updated my server (pax) but I can only join successfully by going to
http://pax.mosquito.net:8000/ and not from the wpilot homepage.
When using the client from the wpilot homepage the login hangs at "Initializing game...".

Perhaps you forgot to update http://jfd.github.com/wpilot/client.html ?

**Comment by jfd** [comment]
@neuhaus the client is updated now.

**Comment by neuhaus** [comment]
Great, thanks!
