### ISSUE TITLE
none of the servers are up

### ISSUE THREAD

**Issue by ghost** [jfd/wpilot#27]
I cant join a game because none of the servers are up
I really wont to play this game with my friends but i cant please tell me why they wont work im on a chrome book with ubuntu on it im using chrome thanks for your time

**Comment by slacktracer** [comment]
Hi, @fishfishfish2104 

I am not part of this project, but I love this game and I have played it with friends a lot a few years ago. I am not playing it these days just because I have less available friends now. =P

So, anyway, I think your best chance to play it is by setting up you own server. It is not that hard...

I do not know what are those servers on the game page but I have never seen them online. I am pretty sure they were gone for good long before I found this game.

I hope you get it running! If you put it on a public server let me know, so I can see if I still got my "skillzs". =P

Now thinking about it, perhaps it would be easy to put online for a week with evennode.com or something... [perhaps...]

**Comment by ghost** [comment]
i dont know how to make a public server if you could tell me how or show me a page that tells me i would

**Comment by slacktracer** [comment]
@fishfishfish2104 

Hey, I am not sure what I would have to do to make it work on EvenNode and I can't find out right now, unfortunately.

You should try to run the game locally first anyway. You have to install node. Do you have node installed? If you do not, I recommend installing latest node with nvm: https://github.com/creationix/nvm

I have a copy of wpilots here: http://anzol.biz/wpilots.zip

But you can download it from github too, I do not think a I changed anything in the code...

There is a extra txt there though, just to remind me how to start the server and select maps. Its content is just:

node wpilots --host 192.168.0.23 --map ./maps/versus.json

What it means is, after you have node installed and the wpilots folder you have to enter it and execute 'node wpilots --host [THE MACHINE LOCAL IP] --map [THE PATH TO THE MAP YOU WANT TO USE]

You need to start with the machine ip so other machines on the local network can join the game.

That is it. It was quick and dirty but that is the general idea.

It works for Linux and should work for windows too...

I do not know your level of experience with js, node etc but you probably can look up possible doubts.

Let me know if it works. =)

No time to review what I just wrote! Bye! Good luck!

If you hit a wall I can try to help again!

**Comment by ghost** [comment]
i got a wpilot server up on my computer put only my computer could join the game im not very good with node or javascript so any help is appreciated thanks ps what do you mean by machine ip what machine? thanks for the help

**Comment by slacktracer** [comment]
Hey, @fishfishfish2104 =)

So, your computer is on your local network, right? You other computers using the internet, and some mobile perhaps. Each one have an IP address. Search to find your computer local IP address.

Right now mine is 192.168.0.64

Therefore I can use the following command to start wpilots.

'node wpilots --host 192.168.0.64'

You are doing something like that already, right? How do you do it? Let me know so I can visualize you situation. =P

Now I can put this address (plus the port the process is running, for example: 192.168.0.64:8000, eight thousand is the default I believe) on some other browser, on other computer perhaps (on your local network), to enter the game.

Good luck.

If you want to follow up we better take this conversation somewhere else. It is not about the project anymore.

Open an issue on my fork of this project (https://github.com/slacktracer/wpilot) if you want any further help. =)
(it is the first I can think of =P)

I suggest you to close this issue.

Thank you! See you!
